Fixing typescript compilation errors
TypeScript 2 currently throws the following compilation errors, if a target project uses this module.

```
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(251,12): error TS6133: 'c' is declared but never used.
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(259,29): error TS6133: 'fn' is declared but never used.
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(279,15): error TS6133: 'event' is declared but never used.
```